services:
  db:
    image: postgres:18-alpine
    container_name: newsdrop-db
    environment:
      POSTGRES_DB: newsdrop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:z
    ports:
      - "5432:5432"

  valkey:
    image: valkey/valkey:9.0-alpine
    container_name: newsdrop-valkey
    ports:
      - "6379:6379"

volumes:
  db-data:
